#sudo docker compose -f docker-compose.staging.yml up --detach
services:
  masoncards:
    container_name: masoncards-staging
    build:
      context: .
      dockerfile: Dockerfile
    image: masoncards-staging:latest
    restart: always
    ports:
        - 9001:3000
    environment:
      - NODE_ENV=staging
    volumes:
      - /etc/tabroom/masoncards.config.js:/masoncards/config/config.js:ro
      - /var/log/masoncards:/var/log/masoncards:rw
      - /var/lib/GeoIP:/geoip:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
