services:
  masoncards:
    container_name: masoncards-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: masoncards-dev:latest
    restart: always
    ports:
        - 8001:3000
    environment:
      - NODE_ENV=development
    volumes:
      - /etc/tabroom/masoncards.config.dev.js:/masoncards/config/config.js:ro
      - /var/log/masoncards:/var/log/masoncards:rw
      - /var/lib/GeoIP:/geoip:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
