version: '3'
services:
  masoncards-cron:
    container_name: masoncards-cron
    image: masoncards-cron:latest
    restart: always
    network_mode: "host"
    environment:
        - PORT=3456
        - NODE_ENV=staging
    volumes:
        - /etc/tabroom/masoncards.config.js:/masoncards/config/config.js:ro
        - /var/log/masoncards:/var/log/masoncards:rw
    cpus: 1
    mem_limit: 4gb
    extra_hosts:
      - "host.docker.internal:host-gateway"
